  
FROM node:lts-alpine as builder

RUN mkdir -p /home/node/api/node_modules && chown -R node:node /home/node/api

WORKDIR /home/node/api

COPY package.json yarn.* ./

USER node

RUN yarn

COPY --chown=node:node . .

FROM node:lts-alpine

WORKDIR /home/node/api
COPY --from=builder /home/node/api .

EXPOSE 3333
CMD ["yarn", "start"]